# Generated by Django 4.2.16 on 2025-12-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='job_role',
            field=models.CharField(default='Freelancer', max_length=255),
        ),
    ]
